import { configure, getStorybookUI } from "@storybook/react-native";
// @ts-ignore this file is autogenerated
import { loadStories } from "./generated-stories";
import "./rn-addons";

configure(() => loadStories(), module);

export default getStorybookUI({});
